### ISSUE TITLE
explore the project and create starter tasks

### ISSUE THREAD

**Issue by the-dagger** [JBossOutreach/certificate-generator-front#1]
Please go through the project, ad create some starter tasks on the GCI dashboard that can help the students work on this project.

cc : @thecreepaccess @prithaupadhyay @koderproxy @vivekktiwari @prateekiiest @dilum1995 @sukhbir-singh @malik-gaurav @yashovardhanagrawal @nikitadhiman

**Comment by nikitadhiman** [comment]
some of the sub-parts that I have in mind, not in any particular order are as follows.
A. For certificate issuers : basic certificate template(s); add fields like name, date, what certificate is for and also any special field they would like to add in the certificate for eg validity of the certificate; unique id for each certificate; notify the student via mail and provide link for the certificate which would be shareable.
B. For students: Make an account on the portal; get all the certificates issued to him/her on the landing page sorted by the latest first; Sharing one or multiple certificates via a link; download certificates.
Feel free to add more, and what tasks we can take up first. so tasks can be created on CGI dashboards

**Comment by vivekktiwari** [comment]
I was thinking for beginner level, we should encourage them to setup the testing softwares likes `Karma` and `Protactor`, and ask them to share the test results with us. This should start them with the basic overview?

**Comment by nikitadhiman** [comment]
yes, basic test and dev setup would anyway be the first task. the tasks I mentioned is the complete overview of the project. we can take up a part of it break into subtasks.

**Comment by vivekktiwari** [comment]
@nikitadhiman yeah, seems good. I am making one for beginners level for basic tests and dev setup. Breaking above mentioned A and B into subtask is a good idea.

**Comment by nikitadhiman** [comment]
go ahead.
hi, this is one very basic task I created. Feel free to edit and add yourself. I could not find any task for introduction to jboss community and hence https://codein.withgoogle.com/dashboard/tasks/5147672898961408/

**Comment by vivekktiwari** [comment]
https://codein.withgoogle.com/dashboard/tasks/6450428418981888/

**Comment by prateekiiest** [comment]
Assigned myself @nikitadhiman @vivekktiwari.
I am looking into which areas i can create tasks

**Comment by dilum1995** [comment]
great..! @nikitadhiman assigned my self for some of the tasks.
