### ISSUE TITLE
Travis CI not configured

### ISSUE THREAD

**Issue by sidhyatikku** [JBossOutreach/certificate-generator-front#237]
Travis CI is not configured on this repo. I will try to configure it.

**Comment by sidhyatikku** [comment]
Resolved #236

**Comment by sidhyatikku** [comment]
@nikitadhiman please activate Travis for this repo 

<img width="1343" alt="screen shot 2018-12-08 at 5 06 37 pm" src="https://user-images.githubusercontent.com/33092447/49685599-b6823a00-fb0b-11e8-95c4-e71927e502e9.png">

**Comment by nikitadhiman** [comment]
Will do in sometime

**Comment by nikitadhiman** [comment]
Done!
