### ISSUE TITLE
Login & Signup page is missing navbar & footer

### ISSUE THREAD

**Issue by sidhyatikku** [JBossOutreach/certificate-generator-front#244]
As per the wireframe of this repo, the `login` & `signup` pages have `appnavbar` & `footer` component but as of now, app `login` & `signup` page doesn't contain `navbar` & `footer`. I would like to work on this issue.

#### Application Login Page Wireframe

![Login](https://raw.githubusercontent.com/JBossOutreach/certificate-generator-front/master/src/assets/wire_login.jpg)

#### Current Login Page

<img width="1680" alt="screen shot 2018-12-09 at 1 15 55 am" src="https://user-images.githubusercontent.com/33092447/49690027-1ef30a80-fb50-11e8-9c72-6bac630771ef.png">

**Comment by sidhyatikku** [comment]
@nikitadhiman Please do have a look.

**Comment by Khukhuna** [comment]
https://github.com/JBossOutreach/certificate-generator-front/pull/174 

**Q:** we are not displaying navbar on login & signup page, right?
**Mentor:** No, because we are already providing those options in the page itself

**Comment by Ananthavijay** [comment]
@sidhyatikku r u working on this or can I take up this?

**Comment by nikitadhiman** [comment]
please provide an update on this, who would be taking this up? @sidhyatikku @Ananthavijay

**Comment by Ananthavijay** [comment]
Can I take up this @sidhyatikku

**Comment by sidhyatikku** [comment]
@Ananthavijay sure you can 👍

**Comment by Ananthavijay** [comment]
Will finish this up by tmrw..taking it..

**Comment by Ananthavijay** [comment]
Done @nikitadhiman  and squashed

**Comment by nikitadhiman** [comment]
will check! thanks for your work @Ananthavijay
