### ISSUE TITLE
Sign up page and sign in page looks different

### ISSUE THREAD

**Issue by Ananthavijay** [JBossOutreach/certificate-generator-front#262]
Will make some changes in the sign-up page and make it look like the sign in page.

**Comment by nikitadhiman** [comment]
@Ananthavijay , any update  on this?

**Comment by nikitadhiman** [comment]
No problem, let us know when done

**Comment by Ananthavijay** [comment]
And @nikitadhiman could u have a look at this PR https://github.com/JBossOutreach/certificate-generator-front/pull/257
